name: Morning session
description: Peer-to-peer code review
title: "[Peer-to-peer Code Review]: "
labels: [Review, Needs Triage]
assignees: "didierganthier"
body:
- type: textarea
  attributes:
    label: Highlights 🚀 
    description: Anything you'd like to highlight about this project.
    placeholder: |
      1. Great PR title and description
      2. Concise commit messages
      3. Descriptive README.md file
  validations:
    required: false
- type: textarea
  attributes:
    label: Suggested Changes 💻 
    description: However, there is always room for improvement.
    placeholder: |
      Add your suggestions here
  validations:
    required: false
- type: textarea
  attributes:
    label: Optional Changes 💭  
    description: These changes are optionals but they would be nice.
    placeholder: |
      Add your suggestions here
  validations:
    required: false
- type: textarea
  attributes:
    label: Useful links 🤔 
    description: |
      Links? References? Anything that will help address the issue

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
 - type: input
   attributes:
     label: Cheers and Happy Coding ✨
     description: "Some encouraging words"
     placeholder: "Good luck with this project and happy hacking 👨‍💻"
   validations:
    required: true
